-- ============================================================
-- 20260505221500_employee_dedup_safe_merge.sql
-- Safe merge duplicate employees and harden NIP uniqueness.
-- ============================================================

-- 1) Harden NIP uniqueness (ignore NULL/blank)
DROP INDEX IF EXISTS employees_nip_unique;
CREATE UNIQUE INDEX IF NOT EXISTS employees_nip_unique
  ON public.employees (nip)
  WHERE nip IS NOT NULL AND btrim(nip) <> '';

-- 2) Merge duplicates by normalized full_name for rows with weak identity:
--    - NPWP empty
--    - NIP empty or autogenerated pattern NIP-XXXXXX
--    This keeps the oldest row as survivor and re-links foreign keys.
DO $$
DECLARE
  grp RECORD;
  survivor uuid;
  loser uuid;
BEGIN
  FOR grp IN
    WITH candidates AS (
      SELECT
        lower(regexp_replace(btrim(full_name), '\s+', ' ', 'g')) AS normalized_name,
        array_agg(id ORDER BY created_at NULLS FIRST, id) AS ids
      FROM public.employees
      WHERE btrim(full_name) <> ''
        AND (npwp IS NULL OR btrim(npwp) = '')
        AND (nip IS NULL OR btrim(nip) = '' OR nip ~ '^NIP-[0-9]+$')
      GROUP BY lower(regexp_replace(btrim(full_name), '\s+', ' ', 'g'))
      HAVING count(*) > 1
    )
    SELECT normalized_name, ids FROM candidates
  LOOP
    survivor := grp.ids[1];

    FOR loser IN SELECT unnest(grp.ids[2:array_length(grp.ids, 1)])
    LOOP
      -- employee_salary_component_amounts has unique(employee_id, template_id)
      INSERT INTO public.employee_salary_component_amounts (employee_id, template_id, amount)
      SELECT survivor, template_id, amount
      FROM public.employee_salary_component_amounts
      WHERE employee_id = loser
      ON CONFLICT (employee_id, template_id) DO UPDATE
      SET amount = EXCLUDED.amount;
      DELETE FROM public.employee_salary_component_amounts WHERE employee_id = loser;

      -- payroll_run_lines: merge possible conflicts on run+employee+project
      WITH moved_non_null AS (
        UPDATE public.payroll_run_lines l
        SET employee_id = survivor
        WHERE l.employee_id = loser
          AND l.project_id IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM public.payroll_run_lines s
            WHERE s.run_id = l.run_id
              AND s.employee_id = survivor
              AND s.project_id = l.project_id
          )
        RETURNING l.id
      ),
      conflict_non_null AS (
        SELECT l.id, l.run_id, l.project_id, l.amount::numeric AS amount
        FROM public.payroll_run_lines l
        WHERE l.employee_id = loser
          AND l.project_id IS NOT NULL
      )
      UPDATE public.payroll_run_lines s
      SET amount = (s.amount::numeric + c.amount)
      FROM conflict_non_null c
      WHERE s.run_id = c.run_id
        AND s.employee_id = survivor
        AND s.project_id = c.project_id;

      DELETE FROM public.payroll_run_lines
      WHERE employee_id = loser
        AND project_id IS NOT NULL;

      WITH moved_null AS (
        UPDATE public.payroll_run_lines l
        SET employee_id = survivor
        WHERE l.employee_id = loser
          AND l.project_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM public.payroll_run_lines s
            WHERE s.run_id = l.run_id
              AND s.employee_id = survivor
              AND s.project_id IS NULL
          )
        RETURNING l.id
      ),
      conflict_null AS (
        SELECT l.id, l.run_id, l.amount::numeric AS amount
        FROM public.payroll_run_lines l
        WHERE l.employee_id = loser
          AND l.project_id IS NULL
      )
      UPDATE public.payroll_run_lines s
      SET amount = (s.amount::numeric + c.amount)
      FROM conflict_null c
      WHERE s.run_id = c.run_id
        AND s.employee_id = survivor
        AND s.project_id IS NULL;

      DELETE FROM public.payroll_run_lines
      WHERE employee_id = loser
        AND project_id IS NULL;

      -- simple FK updates
      IF to_regclass('public.employee_project_assignments') IS NOT NULL THEN
        UPDATE public.employee_project_assignments SET employee_id = survivor WHERE employee_id = loser;
      END IF;
      IF to_regclass('public.employee_contracts') IS NOT NULL THEN
        UPDATE public.employee_contracts SET employee_id = survivor WHERE employee_id = loser;
      END IF;
      IF to_regclass('public.expenses') IS NOT NULL THEN
        UPDATE public.expenses SET employee_id = survivor WHERE employee_id = loser;
      END IF;
      IF to_regclass('public.item_loans') IS NOT NULL THEN
        UPDATE public.item_loans SET employee_id = survivor WHERE employee_id = loser;
      END IF;
      IF to_regclass('public.approval_rules') IS NOT NULL THEN
        UPDATE public.approval_rules SET approver_employee_id = survivor WHERE approver_employee_id = loser;
      END IF;
      IF to_regclass('public.expense_approvals') IS NOT NULL THEN
        UPDATE public.expense_approvals SET approver_employee_id = survivor WHERE approver_employee_id = loser;
      END IF;

      DELETE FROM public.employees WHERE id = loser;
    END LOOP;
  END LOOP;
END
$$;
